email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: sendermail
  password: wmcgtzwnpkmeermd
  from_addr: sender mail
  recipients:
    - receivermail

alert_thresholds:
  critical: 0.9
  high: 0.7
  medium: 0.5
  low: 0.3

alert_intervals:
  critical: 5
  high: 15
  medium: 30
  low: 60
